#' vt_export_json
#'
#' exports a node to suitable json required by voronoi javascript function
#'
#' @param node a Node object generated by \code{\link{vt_create_node}} or returned
#' from  \code{\link{vt_add_nodes}}
#' @param file path where the json should be written to
#'
#' @return NULL
#' @export
#' @seealso vt_create_node vt_add_nodes
#' @examples
#' vt_export_json(n, file=tempfile())
vt_export_json <- function(node, file) {
  stopifnot("Node" %in% class(node))
  stopifnot("R6" %in% class(node))
  cat("writing json to",shQuote(file),"\n")
  cat(toJSON(ToListExplicit(node)), file=file)
  return(invisible(NULL))
}
